export enum Industry {
  TECH = "💻 Tecnologia da Informação (TI e Inovação)",
  FINANCE = "🏦 Financeiro e Bancário",
  HEALTH = "🏥 Saúde e Biotecnologia",
  EDUCATION = "🎓 Educação e Treinamento",
  JURIDICAL = "⚖️ Jurídico e Serviços Legais",
  NGO = "🌍 ONG e Associações",
  LOGISTICS = "🚛 Logística, Transporte e Distribuição",
  MANUFACTURING = "🏭 Indústria e Manufatura",
  MEDIA = "📈 Marketing, Publicidade e Comunicação",
  REAL_ESTATE = "🏠 Imobiliário e Construção",
  RETAIL = "🏪 Comércio e Varejo",
  TOURISM = "🏨 Turismo, Hotelaria e Eventos",
  CONSTRUCTION = "🧱 Construção Civil e Engenharia",
  GOVERNMENT = "🏛️ Setor Público e Governamental",
  ENERGY = "💡 Energia e Sustentabilidade",
  RESEARCH = "🔬 Pesquisa, Ciência e Desenvolvimento",
  OTHER = "🌍 Outros",
}